services:
  mongodb:
    image: mongo:8.0
    container_name: hotel-booking-mongodb
    restart: unless-stopped

    ports:
      - "${MONGO_PORT}:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    volumes:
      - mongodb_data:/data/db

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval \"db.adminCommand('ping').ok\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:8-alpine
    container_name: hotel-booking-redis
    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongodb_data:
    name: hotel-booking-mongodb-data

  redis_data:
    name: hotel-booking-redis-data